import { useEffect, useRef, useState } from "react";
import { PorcupineWorker } from "@picovoice/porcupine-web";
import { WebVoiceProcessor } from "@picovoice/web-voice-processor";

type Options = {
  enabled: boolean;
  onWake: () => void;
  accessKey: string;
  keywordPath: string;
  modelPath: string;
  sensitivity?: number;
};

/**
 * Real wake-word detection via Picovoice Porcupine — a purpose-built,
 * on-device keyword-spotting model, not dictation software repurposed for
 * the job (that's what useWakeWord.ts is). This is what actually closes the
 * gap with real Alexa-grade reliability: it runs entirely locally in a Web
 * Worker (no network round trip per check), reacts in milliseconds, and was
 * trained specifically to recognize one word.
 *
 * Needs two files in frontend/public/ that this hook does NOT generate:
 *  - porcupine_params.pv — Porcupine's generic English model. Already fetched
 *    from Picovoice's public GitHub repo (lib/common/porcupine_params.pv);
 *    it's the same for every app and isn't specific to "Nova."
 *  - nova.ppn — the actual "Nova" keyword model, trained per-project and
 *    per-AccessKey. This one genuinely can't be generated by anyone but you:
 *    it comes from https://console.picovoice.ai (free account → Porcupine →
 *    type "Nova" → target platform "Web (WASM)" → Train → Download).
 *
 * If VITE_PICOVOICE_ACCESS_KEY isn't set, or the .ppn file isn't there yet,
 * this hook simply never activates (`ready` stays false, benign) — see
 * useWakeWordEngine.ts, which falls back to the browser-based recognizer
 * whenever this isn't usable.
 */
export function usePorcupineWakeWord({
  enabled,
  onWake,
  accessKey,
  keywordPath,
  modelPath,
  sensitivity = 0.6,
}: Options) {
  const [ready, setReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const workerRef = useRef<PorcupineWorker | null>(null);
  const onWakeRef = useRef(onWake);
  onWakeRef.current = onWake;

  // Initialize once we have an access key. Independent of `enabled` — we
  // load the model once and then just subscribe/unsubscribe the mic below.
  useEffect(() => {
    if (!accessKey) return;
    let cancelled = false;

    PorcupineWorker.create(
      accessKey,
      { publicPath: keywordPath, label: "nova", sensitivity },
      () => onWakeRef.current(),
      { publicPath: modelPath }
    )
      .then((worker) => {
        if (cancelled) {
          worker.release().catch(() => {});
          worker.terminate();
          return;
        }
        workerRef.current = worker;
        setReady(true);
        setError(null);
      })
      .catch((err: any) => {
        if (cancelled) return;
        console.warn(
          "[porcupine] failed to load — falling back to browser wake word. " +
            "Usually means nova.ppn is missing from frontend/public/, or the access key is wrong:",
          err?.message ?? err
        );
        setError(err?.message ?? "Failed to load the wake-word engine.");
      });

    return () => {
      cancelled = true;
      const worker = workerRef.current;
      if (worker) {
        WebVoiceProcessor.unsubscribe(worker).catch(() => {});
        worker.release().catch(() => {});
        worker.terminate();
        workerRef.current = null;
        setReady(false);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [accessKey, keywordPath, modelPath, sensitivity]);

  // Subscribe/unsubscribe the mic as `enabled` toggles (paused while Nova is
  // recording/thinking/speaking, same as the browser wake-word hook).
  useEffect(() => {
    if (!ready || !workerRef.current) return;
    if (enabled) {
      WebVoiceProcessor.subscribe(workerRef.current).catch((err) => {
        console.error("[porcupine] mic subscribe failed:", err);
        setError(err?.message ?? "Microphone access failed.");
      });
    } else {
      WebVoiceProcessor.unsubscribe(workerRef.current).catch(() => {});
    }
  }, [enabled, ready]);

  return { ready, error };
}
